# nav2_params.yaml  (Humble, TB3 Burger-ish defaults)
amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: /scan
    min_particles: 500
    max_particles: 2000
    laser_min_range: 0.05
    laser_max_range: 3.5
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 1
    transform_tolerance: 0.2
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    kld_err: 0.05
    kld_z: 0.99

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: /home/jimmy/maps/my_map.yaml   # <-- point to your map

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_nav_to_pose_bt_xml: ""
    goal_x_tolerance: 0.05
    goal_y_tolerance: 0.05
    goal_yaw_tolerance: 0.05

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: dwb_core/DWBLocalPlanner
      # Vel limits for TB3
      min_vel_x: 0.0
      max_vel_x: 0.22
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 2.0
      min_speed_xy: 0.0
      max_speed_xy: 0.22
      acc_lim_x: 1.5
      acc_lim_theta: 3.0
      decel_lim_x: -1.5
      decel_lim_theta: -3.0
      # Reduce pointless spins:
      rotate_to_heading: false
      min_x_velocity_threshold: 0.01
      min_theta_velocity_threshold: 0.05
      # Critics:
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 0.1
      use_astar: false

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: nav2_smoother/PathSmoother

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false

# -------------------- Costmaps --------------------
# Common footprint (TB3 radius ~0.105m)
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 10.0
      publish_frequency: 10.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      transform_tolerance: 0.2
      robot_radius: 0.11
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: nav2_costmap_2d/ObstacleLayer
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan
          obstacle_range: 2.5
          raytrace_range: 3.0
      inflation_layer:
        plugin: nav2_costmap_2d/InflationLayer
        inflation_radius: 0.55
        cost_scaling_factor: 3.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      rolling_window: false
      resolution: 0.05
      transform_tolerance: 0.2
      robot_radius: 0.11
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: nav2_costmap_2d/StaticLayer
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: nav2_costmap_2d/ObstacleLayer
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: LaserScan
          obstacle_range: 2.5
          raytrace_range: 3.0
      inflation_layer:
        plugin: nav2_costmap_2d/InflationLayer
        inflation_radius: 0.65
        cost_scaling_factor: 3.0

